name: 'Website Downloader'
description: 'Download a website with all resources (HTML, CSS, JS, images)'
author: 'Nick8582'

inputs:
  url:
    description: 'URL of the website to download'
    required: true
  output_folder:
    description: 'Output directory (default: downloaded_site)'
    required: false
    default: 'downloaded_site'
  depth:
    description: 'Crawl depth (default: 1)'
    required: false
    default: '1'
  ignore_ssl:
    description: 'Ignore SSL certificate verification'
    required: false
    default: 'false'
  user_agent:
    description: 'Custom user agent string'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
      shell: bash

    - name: Run website downloader
      run: |
        python website_downloader.py "${{ inputs.url }}" \
          --output "${{ inputs.output_folder }}" \
          --depth "${{ inputs.depth }}" \
          ${{ inputs.ignore_ssl == 'true' && '--ignore-ssl' || '' }} \
          ${{ inputs.user_agent && format('--user-agent \"{0}\"', inputs.user_agent) || '' }}
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: downloaded-website
        path: ${{ inputs.output_folder }}
