name: Build Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows
        if: runner.os == 'Windows'
        run: |
          cd build
          build_windows.bat
          cd ..
          mkdir artifact
          copy dist\WebsiteDownloader.exe artifact/

      - name: Build Mac
        if: runner.os == 'macOS'
        run: |
          cd build
          chmod +x build_mac.sh
          ./build_mac.sh
          cd ..
          mkdir artifact
          cp -r dist/WebsiteDownloader.app artifact/

      - name: Build Linux
        if: runner.os == 'Linux'
        run: |
          cd build
          chmod +x build_linux.sh
          ./build_linux.sh
          cd ..
          mkdir artifact
          cp dist/website-downloader artifact/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WebsiteDownloader-${{ runner.os }}
          path: artifact/
