name: Скачивание сайта

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL сайта для скачивания'
        required: true
      output_folder:
        description: 'Имя папки для сохранения (по умолчанию downloaded_site)'
        required: false
        default: 'downloaded_site'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Запуск скачивания
        run: |
          python website_downloader.py "${{ inputs.url }}" --output "${{ inputs.output_folder }}"

      - name: Загрузка результатов
        uses: actions/upload-artifact@v4
        with:
          name: скачанный-сайт
          path: ${{ inputs.output_folder }}
